script: "bundle exec rake"

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head

gemfile:
  - Gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/active_record_edge.gemfile
  fast_finish: true
